ding:
  talk:
    corp:
      corpId: ding554e2ce0334dbb5035c2f4657eb6378f
      corpSecret: h10fp5IhC6AUy50CLXZkCwzAZgfh5NUXljL2j0gcNH4eu2AnFn_l5t38Nlkht_05
      SSOsecret: xu10uEa6ftIeVEapwXKyulGqwC08PMxXNzcEHLIq8nZ-IhwylUFTe_r5TkpCN3fQ
      channelSecret: X-bu7pkrQtFagNieXsgg-FlTmEVKHcIk5x7OFW7DQa598PCGP3i8tTQuDBe9h-pD

